prometheus:
  prometheusSpec:
    resources:
      limits:
        memory: 2500Mi

rke2ControllerManager:
  enabled: true

rke2Etcd:
  enabled: true

rke2IngressNginx:
  enabled: true

ingressNginx:
  enabled: true
  namespace: kube-system

rke2Proxy:
  enabled: true

rke2Scheduler:
  enabled: true