controller:
  apisvc:
    type: ClusterIP
  ranchersso:
    enabled: true
  secret:
    enabled: true
    data:
      sysinitcfg.yaml:
        Cluster_Name: demo
      userinitcfg.yaml:
        users:
        - Fullname: admin
          Username: admin
          Role: admin
          Password: adminadmin

k3s:
  enabled: true

global:
  cattle:
    url: https://rancher.susedemo.com/