controller:
  apisvc:
    type: ClusterIP
  replicas: 1
  ranchersso:
    enabled: true

cve:
  scanner:
    replicas: 1

k3s:
  enabled: true

global:
  cattle:
    url: https://rancher.susedemo.com/