ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  host: tetris.kubecon.plgrnd.be
  tls:
  - secretName: tetris-tls
    hosts:
      - tetris.kubecon.plgrnd.be