ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: tetris.kubecon.plgrnd.be
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
  - secretName: tetris-tls
    hosts:
      - tetris.kubecon.plgrnd.be